import { skRoutes } from './skRoutes-v2.js';
// Generated by skroutes plugin
import { routeConfig, type RouteKeys, type RouteTypeMap } from './.generated/skroutes-config.js';

export function createAutoSkRoutes(errorURL: string) {
  return skRoutes({
    config: routeConfig,
    errorURL
  });
}

// Create typed versions of the functions with route key validation and type inference
const defaultInstance = createAutoSkRoutes('/error');

// Wrap the functions to provide type-safe route ID checking and schema type inference
export const urlGenerator = defaultInstance.urlGenerator;

export function pageInfo<Address extends RouteKeys>(
  routeId: Address,
  pageInfo: { params: Record<string, string>; url: { search: string } }
): {
  current: {
    address: Address;
    url: string;
    error: boolean;
    params?: RouteTypeMap[Address]['params'];
    searchParams?: RouteTypeMap[Address]['searchParams'];
  };
  updateParams: (opts: {
    params?: Partial<RouteTypeMap[Address]['params']>;
    searchParams?: Partial<RouteTypeMap[Address]['searchParams']>;
  }) => any;
} {
  return defaultInstance.pageInfo(routeId, pageInfo) as any;
}

export function serverPageInfo<Address extends RouteKeys>(
  routeId: Address,
  data: {
    params: Record<string, string>;
    url: { search: string };
    route: { id: Address };
  }
): {
  current: {
    address: Address;
    url: string;
    error: boolean;
    params?: RouteTypeMap[Address]['params'];
    searchParams?: RouteTypeMap[Address]['searchParams'];
  };
  updateParams: (opts: {
    params?: Partial<RouteTypeMap[Address]['params']>;
    searchParams?: Partial<RouteTypeMap[Address]['searchParams']>;
  }) => any;
} {
  return defaultInstance.serverPageInfo(routeId, data) as any;
}

export function pageInfoStore<Address extends RouteKeys>(config: {
  routeId: Address;
  pageInfo: import('svelte/store').Readable<{
    params: Record<string, string>;
    url: { search: string };
  }>;
  updateDelay?: number;
  onUpdate: (newUrl: string) => unknown;
}) {
  return defaultInstance.pageInfoStore(config);
}

// Export types for consumer use
export type { RouteKeys, RouteTypeMap };