// Auto-generated by skroutes-plugin
import type { StandardSchemaV1 } from '@standard-schema/spec';
import { z } from 'zod';

// Inline schema definitions (extracted from page files)
const schema0_params = z.object({
	id: z.string()
});
const schema0_searchParams = z.object({
	data: z.string(),
	date: z.date().optional()
});

export const routeConfig = {
  '/server/[id]': {
        paramsValidation: schema0_params,
        searchParamsValidation: schema0_searchParams,
      }
} as const;

// Export route keys for type checking
export type RouteKeys = '/server/[id]';

// Export type mapping for schema inference
export type RouteTypeMap = {
  '/server/[id]': { params: StandardSchemaV1.InferOutput<typeof schema0_params>; searchParams: StandardSchemaV1.InferOutput<typeof schema0_searchParams> }
};

// Re-export types for convenience
export type { RouteConfig } from './skRoutes-v2.js';
