name: Run Automatic Checks (Typescript and vitest)
on:
  pull_request:
    branches:
      - master
      - main
      - dev
  push:
    branches:
      - master
      - main
      - dev
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        name: Install node
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7
          run_install: false
      - run: pnpm i
        name: Install Dependencies
      - run: pnpm check
        name: Typescript Check
      - run: pnpm test
        name: run vitest
